#include "kernel/types.h"
#include "kernel/stat.h"
#include "user/user.h"
#include "user/signal.h"

int ouch_count;
void ouch(int sig)
{
    ouch_count++;

    if(ouch_count == 1) {
        printf("\n\tOUCH! - I got signal %d.  That hurt.\n", sig);
    }
    if(ouch_count == 2) {
        // second time call the signal
        printf("\n\tOUCH! - I got signal %d.  I'm nearly dead.\n", sig);
    }
    if(ouch_count == 3) {
        exit(0);
    }
    restore();
}

/*  The main function has to intercept the SIGINT signal generated by ourself
    For the rest of the time, it just executes the loop,
    printing a message once a second.  */

int main() 
{
    ouch_count = 0;
    // installs the new signal handler

    signal(SIGINT, ouch);

    int pid = fork();
    if(pid == 0){
        int i;
        for(i = 0; i < 20; i++) {
            printf("Hello World!\n");
            sleep(1);
        }
    }else{
        sleep(3);
        sendSignal(pid);
        sleep(1);
        sendSignal(pid);
        sleep(1);
        sendSignal(pid);
        int status;
        wait(&status);
        printf("\tExiting naturally\n");
    }

    return 0;
}
